name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        env:
          AQUARITE_API_KEY: ${{ secrets.AQUARITE_API_KEY }}
        run: |
          python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          AQUARITE_API_KEY: ${{ secrets.AQUARITE_API_KEY }}
        run: |
          twine upload dist/*
